name: test

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest

    steps:
      - uses: actions/checkout@v2

      - name: Install pip and requests
        run: |
          apt-get update
          apt-get install -y python3-pip
          pip3 install requests

      - name: Build ROS 2 workspace
        run: |
          # Set up ROS 2 environment and source setup
          source /opt/ros/foxy/setup.bash
          mkdir -p /root/ros2_ws/src
          cd /root/ros2_ws
          # Copy the package and build workspace
          rsync -av ./ /root/ros2_ws/src/mypkg/
          colcon build --symlink-install

      - name: Run tests
        run: |
          source /root/ros2_ws/install/setup.bash
          bash -xv ./src/mypkg/test/test.bash /root

      - name: Upload test logs
        uses: actions/upload-artifact@v2
        with:
          name: weather-publisher-logs
          path: /tmp/weather_publisher.log

